# Generated by Django 5.2.7 on 2025-11-06 02:19

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_add_message_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
