# Generated by Django 5.2.7 on 2025-11-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_conversation_embedding_message_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='embedding',
        ),
    ]
